"""initial schema

Revision ID: 035696badb39
Revises: 
Create Date: 2026-01-27 14:45:36.885959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '035696badb39'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('available_filters')
    op.drop_index(op.f('idx_search_results_search'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('idx_companies_domain'), table_name='companies')
    op.drop_index(op.f('idx_companies_industry'), table_name='companies')
    op.drop_index(op.f('idx_credit_user'), table_name='credit_transactions')
    op.alter_column('exports', 'file_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('prospects', 'linkedin_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_prospects_company'), table_name='prospects')
    op.drop_index(op.f('idx_prospects_email'), table_name='prospects')
    op.drop_index(op.f('idx_search_params'), table_name='search_queries', postgresql_using='gin')
    op.drop_index(op.f('idx_search_user'), table_name='search_queries')
    op.alter_column('users', 'credits_balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'credits_balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('idx_search_user'), 'search_queries', ['user_id'], unique=False)
    op.create_index(op.f('idx_search_params'), 'search_queries', ['query_params'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_prospects_email'), 'prospects', ['email'], unique=False)
    op.create_index(op.f('idx_prospects_company'), 'prospects', ['company_id'], unique=False)
    op.alter_column('prospects', 'linkedin_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('exports', 'file_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_index(op.f('idx_credit_user'), 'credit_transactions', ['user_id'], unique=False)
    op.create_index(op.f('idx_companies_industry'), 'companies', ['industry'], unique=False)
    op.create_index(op.f('idx_companies_domain'), 'companies', ['domain'], unique=False)
    op.create_table('search_results',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('search_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['search_id'], ['search_queries.id'], name=op.f('search_results_search_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('search_results_pkey'))
    )
    op.create_index(op.f('idx_search_results_search'), 'search_results', ['search_id'], unique=False)
    op.create_table('available_filters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('filter_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('filter_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('filter_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_locked', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('credits_required', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('available_filters_pkey')),
    sa.UniqueConstraint('filter_key', name=op.f('available_filters_filter_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
