"""Signal taxonomy — ALL 224 signals from the OutMate Product 2.0 spreadsheet.

Auto-generated from Google Sheets. Each entry maps a signal name to its
category, strength, funnel stage, trigger type, and business rationale.
"""

from __future__ import annotations

import re
from typing import Any, Dict, List, Optional


SIGNAL_TAXONOMY: Dict[str, Dict[str, str]] = {
    "champion_job_change": {"why": "Former buyer lands at a new ICP account and brings prior conviction and budget influence.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Relationship-Based"},
    "champion_promotion": {"why": "Existing user gains more power and can push through a bigger deal or expansion.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Relationship-Based"},
    "new_icp_gtm_leader_hired": {"why": "Fresh VP/Head of Sales, Marketing, or RevOps is motivated to implement new tools quickly.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "new_cro_cco_hired": {"why": "New revenue chief wants measurable wins in first 90 days, including stack upgrades.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Firmographic"},
    "champion_leaves_customer": {"why": "Your internal sponsor exits, raising churn risk but opening new-logo opportunity at their new company.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "History-Based"},
    "multiple_opens_on_outbound_email": {"why": "Repeated opens signal research or internal forwards; timing is right for fast follow-up.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Behavioral"},
    "click_on_outbound_cta": {"why": "Click-through shows curiosity about the specific offer or asset you shared.", "category": "Sales-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "direct_reply_to_outbound": {"why": "Typed response proves engagement; qualifies for immediate human conversation.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Behavioral"},
    "positive_reply_sentiment": {"why": "Language shows interest, alignment, or openness to timing; treat as warm opportunity.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "hard_not_now_reply": {"why": "Prospect declines but specifies timing; tag for scheduled re‑engagement.", "category": "Sales-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "History-Based"},
    "viewed_pricing_page": {"why": "Buyer is benchmarking cost and is usually late in their research process.", "category": "Product-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "viewed_product_demo_tour_page": {"why": "Prospect is validating how the product works, not just what it is.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "viewed_customer_stories": {"why": "Attention on proof points suggests they are building an internal case to buy.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "viewed_integration_page": {"why": "They are checking fit with their current stack, a prerequisite to serious evaluation.", "category": "Product-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Technographic"},
    "company_visited_website_repeatedly": {"why": "Multiple sessions from the same account indicate coordinated interest, not random traffic.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "return_visit_within_7_days": {"why": "Short interval between visits shows the problem is active, not theoretical.", "category": "Product-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Behavioral"},
    "downloads_gated_playbook": {"why": "Willingly trades contact info for expertise, confirming topical interest.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "registers_for_newsletter": {"why": "Opts into ongoing insights, giving consent for softer, educational nurturing.", "category": "Community-Led", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "starts_signup_but_doesn_t_finish": {"why": "Intent is proven but blocked by friction, confusion, or timing; ideal rescue moment.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Symptoms & Signs"},
    "free_trial_signup": {"why": "Explicit signal that they want hands-on experience, not just marketing.", "category": "Product-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "trial_first_login": {"why": "Confirms that signup wasn’t just curiosity; they are willing to invest time.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "trial_completes_onboarding_checklist": {"why": "Hitting all setup steps shows seriousness and near‑term conversion potential.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "trial_reaches_core_value_event": {"why": "User hits the “aha moment” (e.g., first sequence sent); they’ve seen tangible value.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "trial_creates_3_workflows": {"why": "Heavy initial construction indicates strong intent to operationalize.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "trial_invites_teammates": {"why": "Pulling colleagues in means internal validation and higher deal potential.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "trial_inactive_for_3_days": {"why": "Early drop‑off suggests confusion or missing value; urgent candidate for rescue sequence.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Conversion", "trigger_type": "Symptoms & Signs"},
    "trial_expired_with_usage": {"why": "They used the product but didn’t buy; often blocked by process, not fit.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "History-Based"},
    "trial_expired_with_no_usage": {"why": "Poor activation; de‑prioritize or re‑engage later with a radically easier onramp.", "category": "Product-Led", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "History-Based"},
    "paid_user_login_streak": {"why": "Consistent daily or weekly logins show embedded workflows and upsell potential.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Behavioral"},
    "drop_in_active_users": {"why": "Engagement decline signals early churn risk even if renewal is months away.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "seat_utilization_90": {"why": "Org is at or near seat ceiling; natural expansion opportunity.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "workspace_at_usage_limit": {"why": "Hitting data/volume limits proves ROI and justifies a bigger plan.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "new_team_activated_inside_account": {"why": "Another department starts using the product, opening multi‑threaded expansion.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "History-Based"},
    "account_connects_new_integration": {"why": "Signals deeper embedding and readiness for advanced use cases.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Technographic"},
    "account_disconnects_core_integration": {"why": "Integration removal hints at dissatisfaction or stack changes; investigate quickly.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "support_ticket_how_do_we_scale_this": {"why": "Customer is asking for growth guidance, implying expansion readiness.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "support_ticket_too_expensive": {"why": "Pricing friction surfaces; risk of downgrade or churn if unanswered.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "support_ticket_missing_feature": {"why": "Discoverable gap that either blocks adoption or triggers roadmap conversation.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "feature_request_from_power_user": {"why": "This user cares deeply and can be a design partner or reference.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "History-Based"},
    "csm_notes_executive_champion": {"why": "Named senior sponsor improves renewal odds and supports expansion motions.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Relationship-Based"},
    "csm_notes_exec_detractor": {"why": "Senior skeptic can stall deals; requires targeted narrative and proof.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "attended_live_webinar": {"why": "Showed up in real time, dedicating focus and indicating higher engagement.", "category": "Community-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "watched_webinar_recording": {"why": "Asynchronous consumption shows topic interest but lighter urgency.", "category": "Community-Led", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "registered_but_skipped_webinar": {"why": "They cared enough to register, but time or relevance got in the way; send digest.", "category": "Community-Led", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "History-Based"},
    "attended_product_workshop": {"why": "Willingness to dive deep suggests practical interest in implementing.", "category": "Community-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Behavioral"},
    "joined_customer_community": {"why": "Opt‑in to peer group signals long‑term interest and advocacy potential.", "category": "Community-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Relationship-Based"},
    "posts_question_in_community": {"why": "Fresh pain or confusion surfaced publicly; respond with help and expansion context.", "category": "Community-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "answers_peers_questions": {"why": "Acts as informal champion who can become a formal advocate.", "category": "Community-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "History-Based"},
    "participates_in_beta_program": {"why": "Willingness to test new features indicates strategic interest and trust.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Relationship-Based"},
    "opts_into_early_access": {"why": "Wants an edge from new capabilities, enabling targeted upsell later.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Behavioral"},
    "signs_up_for_waitlist": {"why": "Signals explicit desire before product availability, ideal for staged launch.", "category": "Product-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "requests_custom_quote": {"why": "Buying process is active; budget is being sized now.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "requests_security_it_review": {"why": "Deal is serious enough to involve risk and compliance teams.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "asks_for_procurement_paperwork": {"why": "Late‑stage signal; focus on friction removal and closing plan.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "History-Based"},
    "sends_redlines_on_msa": {"why": "Legal is engaged, confirming late funnel; prioritize resolution.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "History-Based"},
    "requests_pilot_or_poc": {"why": "Buyer wants structured validation, often preceding large deals.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "asks_for_roi_model": {"why": "Finance is evaluating impact; provide hard numbers and customer benchmarks.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "asks_for_references": {"why": "Social proof is final hurdle; deal is near decision.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "History-Based"},
    "no_response_after_proposal": {"why": "Silent stall after pricing implies unspoken objections.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "renewal_date_within_90_days": {"why": "Natural moment to assess health and pitch expansion or save.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "History-Based"},
    "renewal_within_30_days_and_low_usage": {"why": "Last‑minute churn risk; urgent re‑engagement required.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "expansion_opportunity_flagged_by_csm": {"why": "Human observation that the account is primed for more value.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Relationship-Based"},
    "customer_attends_qbr": {"why": "Executive participation signals strategic importance of your product.", "category": "Sales-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Relationship-Based"},
    "customer_declines_qbr_invites": {"why": "Lack of time or value perception; may foreshadow renewal issues.", "category": "Sales-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "customer_opens_qbr_deck_repeatedly": {"why": "Deck is circulated internally; expansion conversation is likely brewing.", "category": "Sales-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Behavioral"},
    "positive_nps_response": {"why": "Promoter is good expansion and referral candidate.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "History-Based"},
    "negative_nps_response": {"why": "Detractor requires fast recovery to avoid churn and reputational damage.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "high_csat_trend": {"why": "High satisfaction over time increases odds of multi‑product adoption.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "History-Based"},
    "low_csat_trend": {"why": "Persistent dissatisfaction is a stronger churn predictor than one bad ticket.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "customer_shares_case_study_internally": {"why": "Indicates they want to show off results, which supports expansion.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Behavioral"},
    "customer_agrees_to_public_case_study": {"why": "Confirms strong results and partnership; also boosts acquisition.", "category": "Community-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "History-Based"},
    "customer_speaks_at_your_event": {"why": "Strong advocacy that deepens relationship and drives new pipeline.", "category": "Community-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Relationship-Based"},
    "customer_posts_about_you_on_social": {"why": "Organic praise builds trust and opens warm outbound into their network.", "category": "Community-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Behavioral"},
    "prospect_likes_multiple_founder_posts": {"why": "Repeated engagement suggests alignment with your worldview and pain framing.", "category": "Community-Led", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "prospect_comments_on_founder_content": {"why": "Creates conversational opening for thoughtful outreach.", "category": "Community-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Relationship-Based"},
    "prospect_shares_your_content": {"why": "Uses your POV to educate their network; they see it as credible and useful.", "category": "Community-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "follows_founder_on_x_linkedin": {"why": "Opts into your thinking, making DM outreach more natural.", "category": "Community-Led", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Relationship-Based"},
    "follows_company_page": {"why": "Mild but trackable interest; stronger when combined with other behaviors.", "category": "Community-Led", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "clicks_from_social_to_site": {"why": "Social engagement translates into website exploration; higher buying temperature.", "category": "Community-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "subscribes_to_founder_newsletter": {"why": "Sees founder as trusted voice; good fit for founder‑led outbound nurtures.", "category": "Community-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Relationship-Based"},
    "prospect_appears_on_who_viewed_your_profile": {"why": "Recently looked you up; lightweight curiosity that can justify personalized outreach.", "category": "Sales-Led", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "uses_direct_competitor_core": {"why": "Clear displacement opportunity if pains are present.", "category": "Competitor", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "uses_multiple_direct_competitors": {"why": "Stack sprawl hints at confusion and inefficiency; platform story resonates.", "category": "Competitor", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Technographic"},
    "uses_adjacent_competitor": {"why": "Complementary or wedge opportunity to expand into their workflow.", "category": "Competitor", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "competitor_announces_price_hike": {"why": "Existing customers feel squeezed and re‑evaluate alternatives.", "category": "Competitor", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "competitor_removes_key_feature": {"why": "Creates feature‑gap pain that you can fill.", "category": "Competitor", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "competitor_suffers_outage": {"why": "Reliability concerns spike; time‑sensitive chance to show stability.", "category": "Competitor", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "competitor_security_incident": {"why": "Trust gets shaken; you can lead with compliance and security messaging.", "category": "Competitor", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "competitor_acquired": {"why": "Customers worry about roadmap and support; more open to switching.", "category": "Competitor", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "competitor_sunsets_product": {"why": "Forced migration moment where urgency is baked in.", "category": "Competitor", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "prospect_visits_competitor_comparison_page": {"why": "They are explicitly evaluating you vs others.", "category": "Product-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "searches_brand_vs_competitor_on_site": {"why": "Self‑signaled desire to compare; targeted battlecard outreach fits.", "category": "Product-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Behavioral"},
    "reads_why_switch_from_x_content": {"why": "Interest in leaving current vendor; problem already acknowledged.", "category": "Product-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "prospect_reviews_competitor_on_g2": {"why": "Reveals buyer experience and dissatisfaction you can speak to.", "category": "Competitor", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "prospect_views_your_g2_profile": {"why": "Using third‑party validation to shortlist vendors.", "category": "Product-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "downloads_g2_report_with_you_in_it": {"why": "Category exploration is active; your inclusion builds trust.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "raised_new_funding_round": {"why": "Fresh capital usually brings new GTM experiments and tool budgets.", "category": "Firmographic", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "raised_mega_late_stage_round": {"why": "Pressure to scale quickly makes automation tools attractive.", "category": "Firmographic", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "down_round_announced": {"why": "Strong pressure to improve efficiency and show profitable growth.", "category": "Firmographic", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "public_revenue_growth_30": {"why": "Demonstrated traction; they invest to maintain growth edge.", "category": "Firmographic", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "hiring_20_yoy": {"why": "Headcount expansion requires scalable onboarding and systems.", "category": "Firmographic", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "hiring_spree_in_gtm_roles": {"why": "Big outbound/marketing push where your product can be a force multiplier.", "category": "Firmographic", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "freeze_in_hiring": {"why": "Budget constraints favor tools that automate headcount.", "category": "Firmographic", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "layoffs_impacting_gtm": {"why": "Fewer people must do same work; efficiency narrative lands strongly.", "category": "Firmographic", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "opens_new_regional_office": {"why": "New geography needs GTM motion and tooling from scratch.", "category": "Firmographic", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "launches_new_segment_vertical": {"why": "Fresh ICP tests need structured outbound and workflows.", "category": "Firmographic", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "announces_plg_motion": {"why": "Self‑serve push creates need for signal‑based outbound activation.", "category": "Firmographic", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "announces_outbound_pivot": {"why": "Explicit focus on outbound productivity; high alignment with agentic GTM.", "category": "Firmographic", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "announces_abm_initiative": {"why": "Account‑based strategy depends on signal quality and orchestration.", "category": "Firmographic", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "announces_tech_consolidation_goal": {"why": "They want fewer tools; platform story and agentic workflows resonate.", "category": "Firmographic", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "new_icp_company_created_via_data": {"why": "Net‑new firm that fits ICP now appears in firmographic data.", "category": "Firmographic", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "company_crosses_revenue_band_threshold": {"why": "Graduating from SMB to mid‑market triggers process re‑design and stack changes.", "category": "Firmographic", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "company_crosses_employee_band_threshold": {"why": "More people introduces complexity that software can simplify.", "category": "Firmographic", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "installed_salesforce": {"why": "Known CRM makes integration and workflow story concrete.", "category": "System", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "installed_hubspot": {"why": "Similar to Salesforce, enables CRM‑first orchestration plays.", "category": "System", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "installed_pipedrive_zoho": {"why": "Indicates CRM adoption but often with manual GTM workflows.", "category": "System", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "installed_outreach": {"why": "Suggests mature outbound process ready for smarter signals and agents.", "category": "Technographic", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "installed_salesloft": {"why": "Same as Outreach; integration‑driven workflow plays convert well.", "category": "Technographic", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "installed_apollo_lusha": {"why": "Prospecting‑heavy teams receptive to smarter automation.", "category": "Technographic", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "installed_6sense_clearbit": {"why": "Already investing in intent; you can monetize that intent via agents.", "category": "Technographic", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Technographic"},
    "installed_gong_chorus": {"why": "Conversation data exists, enabling “intent from calls” workflows.", "category": "Technographic", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "installed_intercom_drift": {"why": "Site chat events can trigger AI outbound and follow‑ups.", "category": "Technographic", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "installed_calendly_chili_piper": {"why": "Scheduling layer present; AI can fill and protect calendars.", "category": "Technographic", "strength": "Low", "funnel_stage": "Consideration", "trigger_type": "Technographic"},
    "installed_segment_rudderstack": {"why": "Data infrastructure in place; perfect host for signal routing.", "category": "Technographic", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Technographic"},
    "installed_warehouse_snowflake_bigquery": {"why": "Data‑mature org ready for complex signal aggregation.", "category": "Technographic", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Technographic"},
    "using_spreadsheets_as_crm_job_posts_content": {"why": "Manual GTM signals high pain and low sophistication; needs coaching‑heavy sale.", "category": "Technographic", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "uses_3_disconnected_gtm_tools": {"why": "Fragmented stack wastes GTM time; platform and agents add clear leverage.", "category": "Technographic", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "public_rfp_mentioning_your_category": {"why": "They’re actively shopping for your type of solution.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "job_post_requiring_your_category": {"why": "Hiring for skills in your space signals current or upcoming purchase.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "job_post_asks_for_build_outbound_engine": {"why": "They are about to invest heavily in outbound process and tooling.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "job_post_mentioning_specific_competitors": {"why": "They plan to use or replace those tools; good displacement wedge.", "category": "Competitor", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "job_post_highlighting_ai_in_gtm": {"why": "Leadership expects AI‑driven workflows, aligning strongly with Outmate.", "category": "Firmographic", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "new_icp_founder_raises_seed": {"why": "Early‑stage founder about to design first GTM stack.", "category": "Firmographic", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "founder_posts_about_outbound_pain": {"why": "Strong narrative cue for founder‑to‑founder outreach.", "category": "Community-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "founder_asks_for_tool_recommendations": {"why": "Social proof‑driven purchase underway; join the thread with value.", "category": "Community-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "founder_likes_signal_based_gtm_content": {"why": "Indicates receptiveness to your category framing.", "category": "Community-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "founder_appears_on_gtm_podcasts": {"why": "Demonstrates thoughtfulness about GTM; good candidate for strategic partnership.", "category": "Community-Led", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Relationship-Based"},
    "prospect_attends_industry_conference": {"why": "Buyer is exploring vendors and ideas; good pre‑ and post‑event outreach timing.", "category": "Event", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "prospect_registers_for_your_event": {"why": "Direct opt‑in to your brand; prime target for sequences tied to the event topic.", "category": "Event", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "prospect_visits_event_booth": {"why": "In‑person touch adds trust and heat to pipeline.", "category": "Event", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Relationship-Based"},
    "scanned_badge_at_booth_demo": {"why": "Explicit in‑booth interest; qualifies for rapid SDR follow‑up.", "category": "Event", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Behavioral"},
    "attends_your_talk_workshop": {"why": "Buyer is aligned enough to spend session time with your POV.", "category": "Event", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "schedules_on_site_follow_up_meeting": {"why": "Event‑driven meeting is pipeline in motion; no further warming needed.", "category": "Event", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "partner_referral_submitted": {"why": "Another vendor or agency signals that an account is ready to talk.", "category": "Partner", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Relationship-Based"},
    "partner_co_selling_opportunity_logged": {"why": "Partner is already in the deal; your product adds incremental value.", "category": "Partner", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Relationship-Based"},
    "partner_integration_installed_by_account": {"why": "Shared customer is easier to expand via integrated workflows.", "category": "Partner", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Technographic"},
    "channel_partner_loses_account": {"why": "Displaced partner opens door for your direct relationship.", "category": "Partner", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "agency_posts_case_study_using_your_product": {"why": "Validates success and creates inbound interest in similar accounts.", "category": "Partner", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "History-Based"},
    "agency_prospect_asks_for_ai_gtm_solution": {"why": "Agency needs repeatable stack for multiple clients, multiplying deal size.", "category": "Partner", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "cold_call_connects_with_right_persona": {"why": "Live conversation achieved; should trigger follow‑up tasks and sequences.", "category": "Sales-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "cold_call_booked_meeting": {"why": "Meeting scheduled is one of the strongest sales‑ready signals.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "cold_call_scheduled_but_no_show": {"why": "Interest existed but friction arose; salvage with async resources.", "category": "Sales-Led", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "History-Based"},
    "direct_website_chat_asking_pricing": {"why": "Strong buying intent; route to human fast.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "direct_website_chat_asking_do_you_integrate_with_x": {"why": "Integration question confirms they’re mapping you into their stack.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Technographic"},
    "direct_chat_asking_for_feature_fit": {"why": "Evaluating capability match; good moment for tailored demo.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "lead_responds_to_ai_website_concierge": {"why": "Engages with AI agent on site, showing they are open to automated help.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "lead_uploads_data_sample_in_product": {"why": "Deeper interaction that shows commitment beyond browsing.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "user_configures_outbound_sequence_template": {"why": "Signals readiness to operationalize GTM, not just explore.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "user_activates_ai_agent_for_first_time": {"why": "Crossing the “agent” threshold shows trust in automation.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "user_schedules_first_outbound_campaign": {"why": "Clear sign that GTM engine is being built on your platform.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "user_pauses_all_campaigns": {"why": "Indicates loss of confidence or external change; investigate health.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "user_connects_crm_but_never_syncs": {"why": "Shows intent but technical or process friction; fix quickly.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Conversion", "trigger_type": "Symptoms & Signs"},
    "user_disconnects_crm": {"why": "Major red flag for long‑term retention.", "category": "Product-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "user_exports_data_frequently": {"why": "Heavy usage and dependency; good trigger for higher tier or services.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Behavioral"},
    "workspace_creates_many_custom_fields": {"why": "Organization is tailoring system to their processes, deepening lock‑in.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Behavioral"},
    "workspace_deletes_large_number_of_users": {"why": "Potential downsizing or internal shift; monitor for churn risk.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "customer_opens_changelog_emails": {"why": "Actively tracks new features and may adopt them quickly.", "category": "Product-Led", "strength": "Low", "funnel_stage": "Expansion", "trigger_type": "Behavioral"},
    "customer_uses_new_feature_within_7_days_of_launch": {"why": "Fast adoption suggests product‑market fit for that feature and expansion potential.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Behavioral"},
    "customer_ignores_key_feature_over_90_days": {"why": "Unused value reduces perceived ROI; training or repositioning needed.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "customer_requests_additional_training": {"why": "Desire to deepen usage and results; good expansion moment.", "category": "Sales-Led", "strength": "Medium", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "account_asks_for_sso_enterprise_features": {"why": "Indicates security and scale focus; often precursor to enterprise plan.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "account_asks_for_audit_logs_compliance_docs": {"why": "Security team expectation; deals often large and sticky.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "account_asks_about_data_residency": {"why": "Signals more mature buyers and potential for enterprise pricing.", "category": "Sales-Led", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "account_negotiates_annual_prepay": {"why": "Willingness to commit long term; good time for multi‑year + discount structure.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "History-Based"},
    "account_upgrades_mid_term": {"why": "Indicates recognized value; future expansion likely.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "History-Based"},
    "account_downgrades_mid_term": {"why": "Perceived over‑spend; intervene to re‑prove value.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "Symptoms & Signs"},
    "account_churns_but_champion_stays_in_market": {"why": "Champion can re‑buy at new company or later stage.", "category": "Sales-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Relationship-Based"},
    "former_poc_joins_partner_org": {"why": "New partnership or channel path opens up organically.", "category": "Partner", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Relationship-Based"},
    "strategic_account_mentioned_in_founder_content": {"why": "Publicly named target signals focus and justifies personalized pursuit.", "category": "Sales-Led", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "History-Based"},
    "prospect_domain_appears_in_demo_form_notes": {"why": "Visitor self‑identifies; map them to account and outbound flows.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Behavioral"},
    "multiple_leads_from_same_domain_over_30_days": {"why": "Cross‑functional curiosity suggests broader initiative.", "category": "Product-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "prospect_downloads_implementation_checklist": {"why": "Indicates they’re thinking through rollout, not just evaluation.", "category": "Product-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "prospect_downloads_outbound_playbook": {"why": "Focused interest in GTM execution that your platform powers.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "prospect_downloads_ai_workflow_guide": {"why": "Signals appetite for AI automation around GTM; ideal Outmate ICP.", "category": "Product-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "prospect_attends_customer_stories_event": {"why": "Prefers proof over pitch; they’re close to building business case.", "category": "Event", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Behavioral"},
    "prospect_opens_onboarding_emails_but_doesn_t_log_in": {"why": "Admin is reading but not acting; intervention needed.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Conversion", "trigger_type": "Symptoms & Signs"},
    "prospect_logs_in_via_mobile_only": {"why": "Lightweight engagement; consider simplifying workflows for them.", "category": "Product-Led", "strength": "Low", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "prospect_shares_workspace_with_consultant": {"why": "External advisor involved; they may recommend stack choices.", "category": "Partner", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Relationship-Based"},
    "consultant_agency_starts_multiple_workspaces": {"why": "Signals they are standardizing on your product.", "category": "Partner", "strength": "High", "funnel_stage": "Expansion", "trigger_type": "History-Based"},
    "large_enterprise_domain_signs_up_self_serve": {"why": "PLG‑led beachhead into big account; prioritize for human assist.", "category": "Product-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "self_serve_user_uses_corporate_sso_email": {"why": "Indicates enterprise potential even if they bought a small plan.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Firmographic"},
    "lead_uses_personal_email_but_enterprise_ip": {"why": "Early adopter at big company; needs nurturing into official deal.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "website_session_from_target_abm_list": {"why": "Target account is actively browsing; orchestrate coordinated outreach.", "category": "Product-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "target_abm_account_engages_with_ads": {"why": "Paid engagement proves message‑market resonance.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "target_abm_account_clicks_book_demo_but_drops": {"why": "Strong but incomplete intent; recover via outbound and retargeting.", "category": "Product-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "email_hard_bounce": {"why": "Contact is invalid; update data and find new paths into account.", "category": "System", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "email_soft_bounces_repeatedly": {"why": "Deliverability issues limit reach; fix to avoid silent funnel breaks.", "category": "System", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "domain_added_to_suppression_list": {"why": "Legal or preference block; avoid outreach and respect constraints.", "category": "System", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "History-Based"},
    "lead_unsubscribes_from_marketing": {"why": "Explicit opt‑out; stop nurture but maybe retain product comms.", "category": "System", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "History-Based"},
    "lead_marks_email_as_spam": {"why": "Damages sender reputation; requires list hygiene and messaging rethink.", "category": "System", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "website_shows_cookie_consent_reject_all": {"why": "Data capture is limited; rely more on server‑side or non‑behavioral signals.", "category": "System", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "prospect_uses_ad_blocker": {"why": "Harder to retarget; outbound and owned channels matter more.", "category": "System", "strength": "Low", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "icp_account_uses_many_ai_tools": {"why": "High AI literacy; advanced agentic workflows will resonate.", "category": "Technographic", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "icp_account_uses_zero_ai_tools": {"why": "Greenfield for AI but requires more education and proof.", "category": "Technographic", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Technographic"},
    "org_publishes_ai_strategy_for_gtm_article": {"why": "Public commitment to AI in revenue; strong fit for Outmate.", "category": "Firmographic", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "org_hosts_ai_gtm_meetup_webinar": {"why": "They want to lead in AI; more open to AI‑native platforms.", "category": "Event", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "gtm_leader_posts_about_manual_data_work": {"why": "Shows active frustration with current tools and processes.", "category": "Community-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "gtm_leader_complains_about_sequence_fatigue": {"why": "Outbound response rates are low; your “quality over volume” story fits.", "category": "Community-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "gtm_leader_complains_about_crm_hygiene": {"why": "Data mess blocks accurate GTM; signal‑based automation is compelling.", "category": "Community-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "revops_leader_posts_about_attribution_mess": {"why": "They need better data and workflows, not just dashboards.", "category": "Community-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "sales_leader_posts_looking_for_new_outbound_tools": {"why": "Buying cycle has already started; time to respond with clear proof.", "category": "Community-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "marketing_leader_posts_need_more_pipeline_not_leads": {"why": "Focus is on revenue‑quality pipeline where signal‑based GTM shines.", "category": "Community-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Symptoms & Signs"},
    "prospect_reads_signal_based_gtm_deep_dive": {"why": "They are educating themselves on the exact category you play in.", "category": "Product-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "prospect_reads_agentic_gtm_workflows_article": {"why": "Direct match to Outmate’s agent narrative; very high fit.", "category": "Product-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "In-Market"},
    "prospect_subscribes_to_signals_newsletter": {"why": "Ongoing interest in signals‑driven GTM, priming them for Outmate.", "category": "Community-Led", "strength": "Medium", "funnel_stage": "Awareness", "trigger_type": "Behavioral"},
    "prospect_fills_build_me_a_gtm_workflow_form": {"why": "Explicit demand for tailored automation; hot fit for agents.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "In-Market"},
    "prospect_uploads_icp_list_to_your_product": {"why": "They trust the platform to operate on their core target list.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "prospect_connects_email_calendar": {"why": "Gives your product operational control, indicating high intent.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "prospect_enables_auto_sending_by_agents": {"why": "Hands execution control to AI, showing deep trust and urgency.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "prospect_enables_multi_channel_email_linkedin": {"why": "Ready for serious outbound experimentation; your value can compound quickly.", "category": "Product-Led", "strength": "High", "funnel_stage": "Conversion", "trigger_type": "Behavioral"},
    "prospect_shares_workflow_output_internally": {"why": "Internal forwards show buy‑in from other stakeholders.", "category": "Product-Led", "strength": "Medium", "funnel_stage": "Consideration", "trigger_type": "Behavioral"},
    "prospect_adds_outmate_to_internal_notion_stack_list": {"why": "You’ve made their “tools under evaluation” board; deal is officially live.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "History-Based"},
    "prospect_adds_you_to_security_vendor_list": {"why": "Security team expects to review you, a sign of serious enterprise eval.", "category": "Sales-Led", "strength": "High", "funnel_stage": "Consideration", "trigger_type": "Symptoms & Signs"},
    "prospect_joins_outmate_gtm_lab_cohort": {"why": "Opt‑in to more intensive learning and experimentation; extremely warm for pipeline.", "category": "Community-Led", "strength": "High", "funnel_stage": "Awareness", "trigger_type": "Relationship-Based"},
}


# Keyword patterns for classifying posts against the signal taxonomy.
_KEYWORD_PATTERNS = [
    (re.compile(r'excited to announce|just joined|new role|new position|thrilled to share|starting as|new chapter', re.IGNORECASE), 'champion_job_change'),
    (re.compile(r'promot|new role as (vp|director|head|chief|cto|cmo|cfo|coo|cro)|leveled up', re.IGNORECASE), 'champion_promotion'),
    (re.compile(r'new (cto|cmo|cfo|coo|cro|vp|chief)|welcome our new|joining as (vp|director|head|chief)', re.IGNORECASE), 'new_cro_cco_hired'),
    (re.compile(r'series [a-e]|raised \$|funding round|seed round|venture capital|capital raise|fundrais', re.IGNORECASE), 'raised_new_funding_round'),
    (re.compile(r'leaving|departed|moved on from|last day at|farewell', re.IGNORECASE), 'champion_leaves_customer'),
    (re.compile(r'sounds great|interested|let\'s (chat|talk|connect|meet)|tell me more', re.IGNORECASE), 'positive_reply_sentiment'),
    (re.compile(r'onboarding complete|fully set up|first workflow|getting started with', re.IGNORECASE), 'trial_completes_onboarding_checklist'),
    (re.compile(r'pilot|poc|proof of concept|trial run|evaluation|testing your', re.IGNORECASE), 'requests_pilot_or_poc'),
    (re.compile(r'\broi\b|return on investment|business case|cost.benefit|payback period', re.IGNORECASE), 'asks_for_roi_model'),
    (re.compile(r'crossed \$|revenue milestone|arr.*(million|billion)|mrr growth', re.IGNORECASE), 'new_icp_company_created_via_data'),
    (re.compile(r'installed salesforce|salesforce (migration|implementation|setup)', re.IGNORECASE), 'installed_salesforce'),
    (re.compile(r'installed hubspot|hubspot (migration|implementation|setup)', re.IGNORECASE), 'installed_hubspot'),
    (re.compile(r'installed outreach|outreach\.io|salesloft', re.IGNORECASE), 'installed_outreach'),
    (re.compile(r'spreadsheet.*(crm|tracking|pipeline)|using (excel|sheets).*(crm|pipeline)', re.IGNORECASE), 'uses_adjacent_competitor'),
    (re.compile(r'ai (stack|tools|platform)|multiple ai|ai.native|ai-first', re.IGNORECASE), 'icp_account_uses_many_ai_tools'),
    (re.compile(r'pricing page|check.* pricing|how much does', re.IGNORECASE), 'viewed_pricing_page'),
    (re.compile(r'signed up.*haven\'t|trial.*no activity|created account.*but', re.IGNORECASE), 'free_trial_signup'),
    (re.compile(r'nps.*(8|9|10)|recommend.*strongly|love (this|your) product', re.IGNORECASE), 'high_csat_trend'),
    (re.compile(r'case study|success story|how we (use|built|scaled)|customer story', re.IGNORECASE), 'customer_shares_case_study_internally'),
    (re.compile(r'opened.*email.*times|keeps opening|email engagement', re.IGNORECASE), 'multiple_opens_on_outbound_email'),
    (re.compile(r'downloaded.*whitepaper|ebook|guide.*download|report.*download', re.IGNORECASE), 'downloads_gated_playbook'),
    (re.compile(r'booked.*meeting|scheduled.*call|set up.*demo|meeting booked', re.IGNORECASE), 'cold_call_booked_meeting'),
    (re.compile(r'podcast|appeared on.*show|guest on|interviewed (by|on)', re.IGNORECASE), 'prospect_shares_your_content'),
    (re.compile(r'competitor|vs\.? |alternative to|compared to|switching from|better than.*\b(tool|platform)', re.IGNORECASE), 'uses_direct_competitor_core'),
    (re.compile(r'looking for.*(tool|platform|solution|software)|evaluating|shopping for|alternatives to', re.IGNORECASE), 'sales_leader_posts_looking_for_new_outbound_tools'),
    (re.compile(r'shared.*post|reposted|great (article|insight|post) (from|by)', re.IGNORECASE), 'prospect_shares_your_content'),
    (re.compile(r'follow.*founder|ceo.*follow', re.IGNORECASE), 'follows_founder_on_x_linkedin'),
    (re.compile(r'anyone (know|recommend|use)|looking for (advice|help|recommendations)|question about', re.IGNORECASE), 'posts_question_in_community'),
    (re.compile(r'in my experience|we (use|solved|built)|here\'s (how|what) (we|i)', re.IGNORECASE), 'answers_peers_questions'),
    (re.compile(r'speaking at|presenting at|keynote|panelist|conference talk', re.IGNORECASE), 'customer_speaks_at_your_event'),
    (re.compile(r'attending|headed to|at #.*(conf|summit)|conference|summit|expo', re.IGNORECASE), 'prospect_attends_industry_conference'),
    (re.compile(r'\bipo\b|acquired|acquisition|merger|went public', re.IGNORECASE), 'raised_new_funding_round'),
    (re.compile(r'new (cro|coo)|chief (revenue|operating)|hired.*(cro|coo)', re.IGNORECASE), 'new_cro_cco_hired'),
    (re.compile(r'hiring.*(sales|marketing|sdr|bdr|ae)|open (roles|positions)|we\'re (growing|hiring)', re.IGNORECASE), 'hiring_spree_in_gtm_roles'),
    (re.compile(r'layoff|restructur|reduction in force|let go|downsiz|laying off', re.IGNORECASE), 'layoffs_impacting_gtm'),
    (re.compile(r'ai strategy|ai roadmap|ai.first|ai transformation|adopting ai', re.IGNORECASE), 'org_publishes_ai_strategy_for_gtm_article'),
    (re.compile(r'too many tools|fragmented|tool (sprawl|fatigue)|consolidat|crm.*(broken|mess|hate)', re.IGNORECASE), 'gtm_leader_complains_about_sequence_fatigue'),
    (re.compile(r'looking for.*(tool|platform|solution)|need a better|anyone recommend.*(tool|software)', re.IGNORECASE), 'sales_leader_posts_looking_for_new_outbound_tools'),
    (re.compile(r'ai.*(gtm|sales|marketing|outbound)|gtm.*(ai|agent|automat)', re.IGNORECASE), 'org_publishes_ai_strategy_for_gtm_article'),
    (re.compile(r'signal.based|intent.driven|buying signal|trigger.based', re.IGNORECASE), 'prospect_reads_signal_based_gtm_deep_dive'),
    (re.compile(r'budget.*approv|allocated.*budget|green.?light|approved.*spend', re.IGNORECASE), 'champion_promotion'),
    (re.compile(r'new (firm|company|startup)|just incorporated|launched.*company', re.IGNORECASE), 'new_icp_company_created_via_data'),
    (re.compile(r'thanks for reaching out|got your (email|message)|replying to your', re.IGNORECASE), 'direct_reply_to_outbound'),
    (re.compile(r'churn|cancel|didn\'t renew|lost.*account', re.IGNORECASE), 'account_churns_but_champion_stays_in_market'),
    (re.compile(r'workshop|hands.on|training session|bootcamp', re.IGNORECASE), 'attended_product_workshop'),
    (re.compile(r'joined.*community|member of|welcome to.*community|slack.*group', re.IGNORECASE), 'joined_customer_community'),
    (re.compile(r'partner.*referral|referr|recommended by.*partner', re.IGNORECASE), 'partner_referral_submitted'),
    (re.compile(r'register|signed up for.*webinar|joined.*event|rsvp', re.IGNORECASE), 'prospect_registers_for_your_event'),
    (re.compile(r'competitor.*(price|cost).*increas|rival.*price hike', re.IGNORECASE), 'competitor_announces_price_hike'),
    (re.compile(r'playbook|outbound.*guide|sales.*playbook|gtm.*playbook', re.IGNORECASE), 'prospect_downloads_outbound_playbook'),
]


def classify_signal(post_text: str, signal_type: str = "social_post") -> Dict[str, str]:
    """Classify a post against the 224-signal taxonomy using keyword matching.

    Returns dict with signal_name, why, category, strength, funnel_stage, trigger_type.
    """
    if not post_text:
        return {
            "signal_name": "unknown", "category": "Sales-Led", "strength": "Low",
            "funnel_stage": "Awareness", "trigger_type": "Behavioral",
            "why": "No post text to classify",
        }

    for pattern, signal_key in _KEYWORD_PATTERNS:
        if pattern.search(post_text):
            entry = SIGNAL_TAXONOMY.get(signal_key)
            if entry:
                return {"signal_name": signal_key, **entry}

    return {
        "signal_name": "unknown", "category": "Sales-Led", "strength": "Low",
        "funnel_stage": "Awareness", "trigger_type": "Behavioral",
        "why": "No matching signal pattern found in post text",
    }


def get_signal_entry(key: str) -> Optional[Dict[str, str]]:
    return SIGNAL_TAXONOMY.get(key)


def list_signals_by_category(category: str) -> List[str]:
    return [k for k, v in SIGNAL_TAXONOMY.items() if v["category"] == category]


def list_signals_by_strength(strength: str) -> List[str]:
    return [k for k, v in SIGNAL_TAXONOMY.items() if v["strength"] == strength]


def list_signals_by_funnel_stage(stage: str) -> List[str]:
    return [k for k, v in SIGNAL_TAXONOMY.items() if v["funnel_stage"] == stage]
